Repository FederatedAI/FATE-Test, pull requests merged in 2023-09, with the labels that each got.

#1 migrate fate-test 2.0.0-beta to separate repo
  .gitignore
  README.md
  README_zh.md
  doc/fate_test.md
  python/fate_test/__init__.py
  python/fate_test/_ascii.py
  python/fate_test/_client.py
  python/fate_test/_config.py
  python/fate_test/_flow_client.py
  python/fate_test/_io.py
  python/fate_test/_parser.py
  python/fate_test/fate_test_config.yaml
  python/fate_test/scripts/__init__.py
  python/fate_test/scripts/_options.py
  python/fate_test/scripts/_utils.py
  python/fate_test/scripts/benchmark_cli.py
  python/fate_test/scripts/cli.py
  python/fate_test/scripts/config_cli.py
  python/fate_test/scripts/data_cli.py
  python/fate_test/scripts/generate_mock_data.py
  python/fate_test/scripts/performance_cli.py
  python/fate_test/scripts/testsuite_cli.py
  python/fate_test/utils.py
  python/pyproject.toml
  python/setup.py
  requirements.txt
Labels: documentation, enhancement

#3 update requirements
  python/pyproject.toml
  python/setup.py
  requirements.txt
Labels: documentation

#2 fix requirements(#5008)
  python/requirements.txt
Labels: documentation, enhancement

#4 restore fate_test config
  python/fate_test/fate_test_config.yaml
Labels: enhancement

#5 add release note
  RELEASE.md
Labels: documentation

#7 rm poetry from fate client requirements
  python/pyproject.toml
  python/requirements.txt
  python/setup.py
Labels: documentation, enhancement

#8 edit doc
  README.md
  README_zh.md
  doc/fate_test.md
Labels: documentation

#9 add sklearn requirment
  python/pyproject.toml
  python/requirements.txt
  python/setup.py
Labels: documentation

#6 Merge 2.0.0-beta
  .gitignore
  README.md
  README_zh.md
  RELEASE.md
  doc/fate_test.md
  python/fate_test/__init__.py
  python/fate_test/_ascii.py
  python/fate_test/_client.py
  python/fate_test/_config.py
  python/fate_test/_flow_client.py
  python/fate_test/_io.py
  python/fate_test/_parser.py
  python/fate_test/fate_test_config.yaml
  python/fate_test/scripts/__init__.py
  python/fate_test/scripts/_options.py
  python/fate_test/scripts/_utils.py
  python/fate_test/scripts/benchmark_cli.py
  python/fate_test/scripts/cli.py
  python/fate_test/scripts/config_cli.py
  python/fate_test/scripts/data_cli.py
  python/fate_test/scripts/generate_mock_data.py
  python/fate_test/scripts/performance_cli.py
  python/fate_test/scripts/testsuite_cli.py
  python/fate_test/utils.py
  python/requirements.txt
  python/setup.py
Labels: documentation, enhancement
